"""Puertos e interfaces abstractas del dominio para repositorios (Arquitectura Hexagonal)."""

from typing import Protocol, runtime_checkable
from pathlib import Path
from hera.contracts.track import Track, TrackStatus
from hera.contracts.candidate import Candidate
from hera.contracts.job import Job, JobState
from hera.contracts.crate import Crate


@runtime_checkable
class ITrackRepository(Protocol):
    async def save(self, track: Track) -> Track: ...
    async def get_by_id(self, track_id: str) -> Track | None: ...
    async def find_by_sha256(self, sha256: str) -> Track | None: ...
    async def list_all(self, status: TrackStatus | None = None, limit: int = 100) -> list[Track]: ...
    async def update_status(self, track_id: str, new_status: TrackStatus) -> Track: ...


@runtime_checkable
class ICandidateRepository(Protocol):
    async def save_candidates(self, candidates: list[Candidate]) -> None: ...
    async def get_by_id(self, candidate_id: str) -> Candidate | None: ...
    async def list_by_search_id(self, search_id: str, limit: int = 10) -> list[Candidate]: ...


@runtime_checkable
class IJobRepository(Protocol):
    async def create_job(self, job: Job) -> Job: ...
    async def get_by_id(self, job_id: str) -> Job | None: ...
    async def get_by_idempotency_key(self, key: str) -> Job | None: ...
    async def update_state(
        self,
        job_id: str,
        state: JobState,
        progress: float | None = None,
        attempts: int | None = None,
        result_json: dict | None = None,
        error_code: str | None = None,
        error_message: str | None = None,
    ) -> None: ...
    async def claim_next_queued(self) -> Job | None: ...


@runtime_checkable
class ICrateRepository(Protocol):
    async def save(self, crate: Crate) -> Crate: ...
    async def get_by_id(self, crate_id: str) -> Crate | None: ...
    async def get_by_name(self, name: str) -> Crate | None: ...
    async def add_track(self, crate_id: str, track_id: str, position: int, transition_notes: str | None = None) -> None: ...
    async def list_tracks(self, crate_id: str) -> list[Track]: ...
